<a href="https://colab.research.google.com/github/ayush-kumarsinha/numpy-pandas/blob/main/numpy_part_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [ ]:
l = [1,2,3,4,5,]  # this is a list
# numpy list ko array me convertkar deta hai

In [ ]:
ar = np.array(l)

In [ ]:
ar

array([1, 2, 3, 4, 5])

In [ ]:
type(ar)

numpy.ndarray

In [ ]:
np.array([[1,2], [3,4]])  # this is 2 D array

array([[1, 2],
       [3, 4]])

In [ ]:
np.asarray(l)  # as array is also convert in to the array

array([1, 2, 3, 4, 5])

In [ ]:
a = [2,3,4,5]

In [ ]:
np.asanyarray(a)  # as any array is also convert in to the array

array([2, 3, 4, 5])

In [ ]:
b = np.matrix(1)  # by defolt matrix is given to the 2D array

In [ ]:
b

matrix([[1]])

In [ ]:
np.asanyarray(b)

matrix([[1]])

In [ ]:
a = np.array(l)

In [ ]:
a

array([1, 2, 3, 4, 5])

In [ ]:
c = a  # this is sallo copy # salo copy me agar a ko change karte hai to c bhi change ho jata hai or c ko change karte hai to a bhi change ho jata hai m

In [ ]:
c

array([1, 2, 3, 4, 5])

In [ ]:
a

array([1, 2, 3, 4, 5])

In [ ]:
c[0] = 100

In [ ]:
c

array([100,   2,   3,   4,   5])

In [ ]:
a

array([100,   2,   3,   4,   5])

In [ ]:
d = np.copy(a)  # this is deep copy
# deep copy me agar d ko change karte hai to a pe coi impact nahi hota hai or a ko change karte hai to d pe impact nahi hot hai

In [ ]:
d

array([100,   2,   3,   4,   5])

In [ ]:
a

array([100,   2,   3,   4,   5])

In [ ]:
a[1] = 400


In [ ]:
a


array([100, 400,   3,   4,   5])

In [ ]:
np.fromfunction(lambda i, j : i==j, (3,3))  # 3,3 is generate the 3*3 matrix

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [ ]:
np.fromfunction(lambda i, j : i*j, (3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [ ]:
iterable = (i*i for i in range(5))

In [ ]:
np.fromiter(iterable,float)  # iter se bhi hamm lig array bana sakte hai

array([ 0.,  1.,  4.,  9., 16.])

In [ ]:
np.fromstring('234 234', sep=' ')  #

array([234., 234.])

In [ ]:
np.fromstring('4,5', sep=',')

array([4., 5.])

# Numpy -- Data Types.

In [ ]:
l = [2,3,4,5,6]

In [ ]:
ar = np.array(l)

In [ ]:
ar

array([2, 3, 4, 5, 6])

In [ ]:
ar.ndim  # it is showing in to the dimension of array

1

In [ ]:
ar2 = np.array([[1,2,3,4], [2,3,4,5]])

In [ ]:
ar2.ndim

2

In [ ]:
ar.size

5

In [ ]:
ar2.size

8

In [ ]:
ar.shape  # 5 is represent the row

(5,)

In [ ]:
ar2.shape  # 2 is represent the row
# 4 is represent the column

(2, 4)

In [ ]:
ar.dtype

dtype('int64')

In [ ]:
ar2.dtype  # dtype is show the data type

dtype('int64')

In [ ]:
ar22 = np.array([[1.4,45,45],[23,45,66]])

In [ ]:
ar22

array([[ 1.4, 45. , 45. ],
       [23. , 45. , 66. ]])

In [ ]:
ar22.dtype

dtype('float64')

In [ ]:
range(5)

range(0, 5)

In [ ]:
list(range(5))  # range is given always integer number

[0, 1, 2, 3, 4]

In [ ]:
list(range(2.5,8)) # range function is not giv the floting value

TypeError: 'float' object cannot be interpreted as an integer

In [ ]:
np.arange(2.3,5.6)  # arange is given always float number

array([2.3, 3.3, 4.3, 5.3])

In [ ]:
np.arange(2.3,5.6,.3)  # .3 is showing the gape of the value

array([2.3, 2.6, 2.9, 3.2, 3.5, 3.8, 4.1, 4.4, 4.7, 5. , 5.3])

In [ ]:
# convert in to the list
list(np.arange(2.3,5.6,.3))

[np.float64(2.3),
 np.float64(2.5999999999999996),
 np.float64(2.8999999999999995),
 np.float64(3.1999999999999993),
 np.float64(3.499999999999999),
 np.float64(3.799999999999999),
 np.float64(4.099999999999999),
 np.float64(4.399999999999999),
 np.float64(4.699999999999998),
 np.float64(4.999999999999998),
 np.float64(5.299999999999998)]

In [ ]:
# linspace eak range leta hai aur uko devide kar deta hai
np.linspace(1,5,10)  # 1,5 is a line and usko 10 part me devide kar deta hai

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [ ]:
np.zeros((5))  # THIS IS ZERO MATRIX

array([0., 0., 0., 0., 0.])

In [ ]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.zeros((3,4,2))  # THIS IS 3d array

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [ ]:
np.zeros((3,4,2,3))  # this is 4D array

array([[[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]]])

In [ ]:
# generate the ones
np.ones(4)

array([1., 1., 1., 1.])

In [ ]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.ones((2,3,2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [ ]:
on = np.ones((2,3,2))

In [ ]:
on

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [ ]:
on + 5  # add 5 all the element

array([[[6., 6.],
        [6., 6.],
        [6., 6.]],

       [[6., 6.],
        [6., 6.],
        [6., 6.]]])

In [ ]:
on*4

array([[[4., 4.],
        [4., 4.],
        [4., 4.]],

       [[4., 4.],
        [4., 4.],
        [4., 4.]]])

In [ ]:
# generate the empty array
np.empty((3,6))

array([[1.15629586e-315, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000]])

In [ ]:
# generate the edentity matrix  jiska deagonal element 1 hota hai aur sab zero hota hai
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [2]:
np.logspace(2,5, 10) # log space in b/w 2 and 5 ke bitch me 10 go ka log nikal kar ke deta hai

array([   100.        ,    215.443469  ,    464.15888336,   1000.        ,
         2154.43469003,   4641.58883361,  10000.        ,  21544.34690032,
        46415.88833613, 100000.        ])

In [4]:
np.random.randn(3,4) #  ye random data produce karta hai

array([[ 0.64709468, -1.08137214, -1.48152172, -0.80715537],
       [-1.73759863, -0.38657887, -0.92398404, -2.29175118],
       [ 0.39583024, -1.28552066,  0.03394618,  1.06184555]])

In [5]:
arr = np.random.randn(3,4)

In [6]:
import pandas as pd

In [7]:
pd.DataFrame(arr)

0         1         2         3
0 -0.781425 -1.903073  0.726541 -1.992956
1 -0.371627  1.476430  0.479240 -1.207490
2  1.211602  0.203266  0.717139 -1.186006

In [8]:
np.random.rand(3,4)

array([[0.69621835, 0.97060799, 0.35614516, 0.18549146],
       [0.30493005, 0.26586276, 0.82799269, 0.37290007],
       [0.59098014, 0.26819475, 0.09253826, 0.12118106]])

In [10]:
np.random.randint(1,110,(3,4))  # it is given the integer value

array([[66, 86, 84, 23],
       [58, 70, 81, 99],
       [91, 96, 84, 88]])

In [11]:
# it is convert also a dataframe
pd.DataFrame(np.random.randint(1,110,(300,400)))

0    1    2    3    4    5    6    7    8    9    ...  390  391  392  \
0     15    9   37   98   29   53   36   77   98   18  ...   98   63    7   
1     49   19   92   23   63   30   24  101   63   51  ...  100   28   53   
2     77   27   49   82   38   42   64    4   55   66  ...   71   66   66   
3      4  105  101   72    6    3    4   16   45   56  ...   46   79   56   
4     85   94  105  105   68   33   65   23   93   63  ...   13   53    1   
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
295   21   29   90   28   68   79   52  105   46   96  ...   10   68   72   
296   91   50   14   49   72   11   18   86   96   44  ...   26   21   98   
297   74   82   82   65   22   75   78   18   41  109  ...   41   88   29   
298   23   72  102   37   77   82   36   99   84   97  ...   94   93   94   
299   11   42   89   72   39   30   75   68   10    9  ...   16   57   33   

     393  394  395  396  397  398  399  
0     16   34    6   44   49   88   89  
1     60   13    6    2   78   13   63  
2     67   88   71  101   21   99    4  
3     26   96    4   76    2   58   22  
4     15   52   60   90   70   73   29  
..   ...  ...  ...  ...  ...  ...  ...  
295   53   62  101   20   40    2   27  
296   33  103    9   55    6   11   80  
297   67   34    5   80   11   10   84  
298   60    6   93   77    8    6   67  
299   80   25   51   94   67   53  109  

[300 rows x 400 columns]

In [12]:
# it is also convert in to the csv file
pd.DataFrame(np.random.randint(1,110,(300,400))).to_csv('test.csv')

In [13]:
arr = np.random.rand(3,4)

In [14]:
arr

array([[0.7704032 , 0.99186603, 0.7661747 , 0.11386935],
       [0.09473033, 0.5586884 , 0.64300112, 0.04203719],
       [0.4937736 , 0.63386494, 0.21053343, 0.93728745]])

In [16]:
arr.reshape(6,2) #  isse reshape hota hai

array([[0.7704032 , 0.99186603],
       [0.7661747 , 0.11386935],
       [0.09473033, 0.5586884 ],
       [0.64300112, 0.04203719],
       [0.4937736 , 0.63386494],
       [0.21053343, 0.93728745]])

In [18]:
rre= arr.reshape(6,-13488955)

In [21]:
rre

array([[0.7704032 , 0.99186603],
       [0.7661747 , 0.11386935],
       [0.09473033, 0.5586884 ],
       [0.64300112, 0.04203719],
       [0.4937736 , 0.63386494],
       [0.21053343, 0.93728745]])

In [22]:
rre[1][1]  # we are also perform the indexing and slicing operator

np.float64(0.11386934517842717)

In [23]:
rre[2:5,1]

array([0.5586884 , 0.04203719, 0.63386494])

In [24]:
arr = np.random.randint(1,100,(5,5))

In [25]:
arr

array([[91,  6, 70, 62, 68],
       [53, 34, 66, 94, 53],
       [13, 63, 68, 14, 69],
       [31, 62, 71, 88, 96],
       [58, 56, 73, 45, 85]])

In [26]:
arr>50

array([[ True, False,  True,  True,  True],
       [ True, False,  True,  True,  True],
       [False,  True,  True, False,  True],
       [False,  True,  True,  True,  True],
       [ True,  True,  True, False,  True]])

In [27]:
arr[arr>50]

array([91, 70, 62, 68, 53, 66, 94, 53, 63, 68, 69, 62, 71, 88, 96, 58, 56,
       73, 85])

In [28]:
arr

array([[91,  6, 70, 62, 68],
       [53, 34, 66, 94, 53],
       [13, 63, 68, 14, 69],
       [31, 62, 71, 88, 96],
       [58, 56, 73, 45, 85]])

In [29]:
arr[2:4, [1,2]]

array([[63, 68],
       [62, 71]])

In [30]:
arr[0][0]= 5000

In [31]:
arr

array([[5000,    6,   70,   62,   68],
       [  53,   34,   66,   94,   53],
       [  13,   63,   68,   14,   69],
       [  31,   62,   71,   88,   96],
       [  58,   56,   73,   45,   85]])

# function of the array

In [35]:
arr1 = np.random.randint(1,3, (3,3))
arr2 = np.random.randint(1,3, (3,3))

In [36]:
arr1

array([[2, 1, 2],
       [1, 1, 1],
       [2, 2, 2]])

In [37]:
arr2

array([[2, 1, 1],
       [2, 1, 2],
       [1, 2, 2]])

In [38]:
arr1+arr2

array([[4, 2, 3],
       [3, 2, 3],
       [3, 4, 4]])

In [39]:
arr1-arr2

array([[ 0,  0,  1],
       [-1,  0, -1],
       [ 1,  0,  0]])

In [40]:
arr1/arr2

array([[1. , 1. , 2. ],
       [0.5, 1. , 0.5],
       [2. , 1. , 1. ]])

In [41]:
arr1*arr2  # this is not a matrix multiplication

array([[4, 1, 2],
       [2, 1, 2],
       [2, 4, 4]])

In [42]:
arr1@arr2  # this is a matrix multiplication

array([[ 8,  7,  8],
       [ 5,  4,  5],
       [10,  8, 10]])

In [43]:
arr1/0

/tmp/ipython-input-1510032488.py:1: RuntimeWarning: divide by zero encountered in divide
  arr1/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [44]:
arr1+100

array([[102, 101, 102],
       [101, 101, 101],
       [102, 102, 102]])

In [45]:
arr1**2  # this is power symble

array([[4, 1, 4],
       [1, 1, 1],
       [4, 4, 4]])

# BROADCASTING

In [48]:
arr = np.zeros((4,4))

In [49]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [50]:
row = np.array([1,2,3,4])

In [51]:
row

array([1, 2, 3, 4])

In [52]:
arr+row  # this is the addision perform the row wise

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [53]:
col = np.array([[1,2,3,4]])

In [54]:
col.T

array([[1],
       [2],
       [3],
       [4]])

In [55]:
col

array([[1, 2, 3, 4]])

In [56]:
col.T + arr # this the perform the addision for column wise

array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.]])

In [57]:
arr1 = np.random.randint(1,4,(3,4))

In [58]:
arr1

array([[2, 2, 3, 1],
       [2, 1, 2, 3],
       [1, 2, 1, 2]])

In [59]:
np.square(arr1)

array([[4, 4, 9, 1],
       [4, 1, 4, 9],
       [1, 4, 1, 4]])

In [60]:
np.exp(arr)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [61]:
np.log10(arr1)

array([[0.30103   , 0.30103   , 0.47712125, 0.        ],
       [0.30103   , 0.        , 0.30103   , 0.47712125],
       [0.        , 0.30103   , 0.        , 0.30103   ]])