<a href="https://colab.research.google.com/github/ayush-kumarsinha/numpy-pandas/blob/main/Numpy_part_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy - array Manipulation

In [2]:
import numpy as np

In [3]:
arr = np.random.randint(1,10,(3,4))  # (3,4) is a dimension isko dusra dimension me convert karna hai

In [4]:
arr

array([[4, 9, 4, 4],
       [5, 1, 3, 9],
       [2, 1, 1, 8]])

In [5]:
arr.reshape(6,2)

array([[4, 9],
       [4, 4],
       [5, 1],
       [3, 9],
       [2, 1],
       [1, 8]])

In [6]:
arr.reshape(2,6)

array([[4, 9, 4, 4, 5, 1],
       [3, 9, 2, 1, 1, 8]])

In [7]:
arr.reshape(2,-242342)

array([[4, 9, 4, 4, 5, 1],
       [3, 9, 2, 1, 1, 8]])

In [8]:
arr.T  # T jo hai array ko rocate kar deta hai

array([[4, 5, 2],
       [9, 1, 1],
       [4, 3, 1],
       [4, 9, 8]])

In [9]:
arr

array([[4, 9, 4, 4],
       [5, 1, 3, 9],
       [2, 1, 1, 8]])

In [ ]:
arr.flatten()  #  flatten array ko one dimension me convert kar deta hai

In [10]:
arr1 = np.array([1,2,3,3,4])

In [11]:
arr1.ndim

1

In [12]:
np.expand_dims(arr1,axis=1)  # expend 1 dimension ko 2 dimension me convert karta hai , axis ka matlab hai ki wo one column me devide karta hai

array([[1],
       [2],
       [3],
       [3],
       [4]])

In [14]:
np.expand_dims(arr1, axis=0)

array([[1, 2, 3, 3, 4]])

In [16]:
arr

array([[4, 9, 4, 4],
       [5, 1, 3, 9],
       [2, 1, 1, 8]])

In [17]:
np.squeeze(arr)

array([[4, 9, 4, 4],
       [5, 1, 3, 9],
       [2, 1, 1, 8]])

In [18]:
data = np.array([[1],[2],[3]])

In [19]:
data

array([[1],
       [2],
       [3]])

In [ ]:
np.squeeze(data)  # sqeeze one column ke data ko one dimension me convert karta hai

In [20]:
arr1

array([1, 2, 3, 3, 4])

In [21]:
np.repeat(arr1,3)  # repeate element ko repeate karta hai

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 3, 3, 3, 4, 4, 4])

In [ ]:
np.roll

In [22]:
np.roll(arr1,2)  # roll array ka element ko ghumata hai ex. 2 ka matlab hai 2 place rocate karna

array([3, 4, 1, 2, 3])

In [23]:
np.roll(arr1,3)

array([3, 3, 4, 1, 2])

In [24]:
np.diag(arr1) # ye one dimension array ko diagonal me rakh deta hai

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 3, 0],
       [0, 0, 0, 0, 4]])

# Numpy - Binary Operation

In [25]:
arr1 = np.random.randint(1,10, (3,4))

In [26]:
arr1

array([[1, 9, 6, 1],
       [7, 3, 8, 9],
       [2, 8, 6, 9]])

In [27]:
arr2 = np.random.randint(1,10, (3,4))

In [28]:
arr2

array([[3, 4, 2, 3],
       [7, 2, 4, 3],
       [6, 7, 2, 5]])

In [29]:
arr1+arr2

array([[ 4, 13,  8,  4],
       [14,  5, 12, 12],
       [ 8, 15,  8, 14]])

In [30]:
arr1-arr2

array([[-2,  5,  4, -2],
       [ 0,  1,  4,  6],
       [-4,  1,  4,  4]])

In [31]:
arr1/arr2

array([[0.33333333, 2.25      , 3.        , 0.33333333],
       [1.        , 1.5       , 2.        , 3.        ],
       [0.33333333, 1.14285714, 3.        , 1.8       ]])

In [32]:
arr1*arr2

array([[ 3, 36, 12,  3],
       [49,  6, 32, 27],
       [12, 56, 12, 45]])

In [33]:
arr1%arr2

array([[1, 1, 0, 1],
       [0, 1, 0, 0],
       [2, 1, 0, 4]])

In [35]:
arr1**arr2

array([[      1,    6561,      36,       1],
       [ 823543,       9,    4096,     729],
       [     64, 2097152,      36,   59049]])

In [36]:
arr1 & arr2

array([[1, 0, 2, 1],
       [7, 2, 0, 1],
       [2, 0, 2, 1]])

In [37]:
arr1

array([[1, 9, 6, 1],
       [7, 3, 8, 9],
       [2, 8, 6, 9]])

In [38]:
arr2

array([[3, 4, 2, 3],
       [7, 2, 4, 3],
       [6, 7, 2, 5]])

In [39]:
~arr1  # this is negate operation

array([[ -2, -10,  -7,  -2],
       [ -8,  -4,  -9, -10],
       [ -3,  -9,  -7, -10]])

In [40]:
arr1|arr2  # this is or operatoe

array([[ 3, 13,  6,  3],
       [ 7,  3, 12, 11],
       [ 6, 15,  6, 13]])

In [42]:
arr1>arr2

array([[False,  True,  True, False],
       [False,  True,  True,  True],
       [False,  True,  True,  True]])

# Numpy - String Function

In [43]:
np.array(['ayush', 'kumar'])

array(['ayush', 'kumar'], dtype='<U5')

In [44]:
arr = np.array(['ayush', 'kumar'])

In [45]:
arr

array(['ayush', 'kumar'], dtype='<U5')

In [46]:
np.char.upper(arr)

array(['AYUSH', 'KUMAR'], dtype='<U5')

In [47]:
np.char.title(arr)

array(['Ayush', 'Kumar'], dtype='<U5')

In [49]:
np.char.capitalize(arr)

array(['Ayush', 'Kumar'], dtype='<U5')

# Numpy - Mathematical Function.

In [50]:
arr1

array([[1, 9, 6, 1],
       [7, 3, 8, 9],
       [2, 8, 6, 9]])

In [51]:
np.sin(arr1)

array([[ 0.84147098,  0.41211849, -0.2794155 ,  0.84147098],
       [ 0.6569866 ,  0.14112001,  0.98935825,  0.41211849],
       [ 0.90929743,  0.98935825, -0.2794155 ,  0.41211849]])

In [52]:
np.cos(arr1)

array([[ 0.54030231, -0.91113026,  0.96017029,  0.54030231],
       [ 0.75390225, -0.9899925 , -0.14550003, -0.91113026],
       [-0.41614684, -0.14550003,  0.96017029, -0.91113026]])

In [53]:
np.tan(arr1)

array([[ 1.55740772, -0.45231566, -0.29100619,  1.55740772],
       [ 0.87144798, -0.14254654, -6.79971146, -0.45231566],
       [-2.18503986, -6.79971146, -0.29100619, -0.45231566]])

In [54]:
np.tanh(arr1)

array([[0.76159416, 0.99999997, 0.99998771, 0.76159416],
       [0.99999834, 0.99505475, 0.99999977, 0.99999997],
       [0.96402758, 0.99999977, 0.99998771, 0.99999997]])

In [55]:
np.log10(arr1)

array([[0.        , 0.95424251, 0.77815125, 0.        ],
       [0.84509804, 0.47712125, 0.90308999, 0.95424251],
       [0.30103   , 0.90308999, 0.77815125, 0.95424251]])

In [56]:
np.exp(arr1)

array([[2.71828183e+00, 8.10308393e+03, 4.03428793e+02, 2.71828183e+00],
       [1.09663316e+03, 2.00855369e+01, 2.98095799e+03, 8.10308393e+03],
       [7.38905610e+00, 2.98095799e+03, 4.03428793e+02, 8.10308393e+03]])

In [58]:
np.sqrt(arr1)

array([[1.        , 3.        , 2.44948974, 1.        ],
       [2.64575131, 1.73205081, 2.82842712, 3.        ],
       [1.41421356, 2.82842712, 2.44948974, 3.        ]])

In [60]:
np.power(arr1,2)

array([[ 1, 81, 36,  1],
       [49,  9, 64, 81],
       [ 4, 64, 36, 81]])

In [61]:
np.mean(arr1)

np.float64(5.75)

In [62]:
np.median(arr1)

np.float64(6.5)

In [63]:
np.std(arr1)

np.float64(3.031088913245535)

In [64]:
np.var(arr1)

np.float64(9.1875)

In [66]:
np.min(arr1)

np.int64(1)

In [67]:
np.max(arr1)

np.int64(9)