<a href="https://colab.research.google.com/github/ayush-kumarsinha/numpy-pandas/blob/main/numpy_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Sort, Search and Count Function in Numpy

In [1]:
import numpy as np

In [2]:
arr = np.array([4,3,4,5,6,72,3,3,455,5,6])

In [3]:
arr

array([  4,   3,   4,   5,   6,  72,   3,   3, 455,   5,   6])

In [5]:
np.sort(arr)

array([  3,   3,   3,   4,   4,   5,   5,   6,   6,  72, 455])

In [7]:
np.searchsorted(arr,32)  # 32 kis place pe jayega

np.int64(5)

In [8]:
arr1 = np.array([0,345,454,0,0,0,0,0])

In [9]:
np.count_nonzero(arr1)

2

In [10]:
arr

array([  4,   3,   4,   5,   6,  72,   3,   3, 455,   5,   6])

In [11]:
np.where(arr > 6)

(array([5, 8]),)

In [12]:
np.where(arr > 6)

(array([5, 8]),)

In [13]:
np.extract(arr>3, arr)

array([  4,   4,   5,   6,  72, 455,   5,   6])

# NUMPY - BYTE SWAPPING

In [17]:
  arr.byteswap()

array([  288230376151711744,   216172782113783808,   288230376151711744,
         360287970189639680,   432345564227567616,  5188146770730811392,
         216172782113783808,   216172782113783808, -4107001385185181696,
         360287970189639680,   432345564227567616])

# Numpy - Copies and Views.

In [18]:
arr

array([  4,   3,   4,   5,   6,  72,   3,   3, 455,   5,   6])

In [19]:
a = np.copy(arr)

In [21]:
b = arr.view()

In [22]:
arr

array([  4,   3,   4,   5,   6,  72,   3,   3, 455,   5,   6])

In [23]:
b[0] = 67

In [24]:
arr

array([ 67,   3,   4,   5,   6,  72,   3,   3, 455,   5,   6])

# Numpy - Matrix Library.

In [25]:
import numpy.matlib as nm  # this is matrix library

In [26]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [27]:
nm.ones((3,4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [28]:
nm.eye(5) # identity matrix

matrix([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

# Numpy - Linear Al=lgebra

In [29]:
arr1 = np.random.randint([[2,3],[4,5]])

In [30]:
arr2 = np.random.randint([[5,3],[2,5]])

In [31]:
np.dot(arr1,arr2)

array([[2, 4],
       [2, 7]])

In [33]:
arr1@arr2

array([[2, 4],
       [2, 7]])